TARGET : = iphone : clang : 14.5 : 14.0

                    include
                    $(THEOS) /
                    makefiles /
                    common.mk

                        BUNDLE_NAME = ShowTouchesPreferenceBundle

               ShowTouchesPreferenceBundle_FILES =
                   JASRootListController.m ShowTouchesPreferenceBundle_FRAMEWORKS =
                       UIKit ShowTouchesPreferenceBundle_PRIVATE_FRAMEWORKS =
                           Preferences ShowTouchesPreferenceBundle_INSTALL_PATH =
                               / Library / PreferenceBundles ShowTouchesPreferenceBundle_CFLAGS =
                                   -fobjc - arc

                                                    include $(THEOS_MAKE_PATH) /
                                                bundle.mk
